#ifndef lala_op_code_h
#define lala_op_code_h


// ┌───────┐
// │ Types │
// └───────┘

typedef enum {
    // Empty
    OP_EMPTY,

    // Stack
    OP_PUSH_TRUE,
    OP_PUSH_FALSE,
    OP_PUSH_BYTE,
    OP_PUSH_INT,
    OP_PUSH_FLOAT,
    OP_PUSH_ADDRESS,
    OP_POP_BYTE,
    OP_POP_INT,
    OP_POP_FLOAT,
    OP_POP_ADDRESS,
    OP_POP_BYTES,

    // Heap
    OP_LOAD_CONSTANT,
    OP_DEFINE_ON_HEAP,
    
    OP_GET_BYTE_FROM_HEAP,
    OP_GET_INT_FROM_HEAP,
    OP_GET_FLOAT_FROM_HEAP,
    OP_GET_ADDRESS_FROM_HEAP,

    OP_SET_BYTE_ON_HEAP,
    OP_SET_INT_ON_HEAP,
    OP_SET_FLOAT_ON_HEAP,
    OP_SET_ADDRESS_ON_HEAP,

    // Logical
    OP_OR,
    OP_AND,
    OP_NEGATE_BOOL,

    // Comparison
    OP_EQUALS_BOOL,
    OP_EQUALS_INT,
    OP_EQUALS_FLOAT,
    OP_EQUALS_STRING,
    OP_LESS_INT,
    OP_LESS_FLOAT,
    OP_LESS_STRING,
    OP_GREATER_INT,
    OP_GREATER_FLOAT,
    OP_GREATER_STRING,

    // Math
    OP_ADD_INT,
    OP_ADD_FLOAT,
    OP_MULTIPLY_INT,
    OP_MULTIPLY_FLOAT,
    OP_DIVIDE_INT,
    OP_DIVIDE_FLOAT,
    OP_MODULO_INT,
    OP_MODULO_FLOAT,
    OP_NEGATE_INT,
    OP_NEGATE_FLOAT,

    // String
    OP_CONCATENATE,

    // Cast
    OP_CAST_FLOAT_TO_INT,
    OP_CAST_INT_TO_FLOAT,
    OP_CAST_BOOL_TO_STRING,
    OP_CAST_INT_TO_STRING,
    OP_CAST_FLOAT_TO_STRING,

    // Variables
    OP_GET_LOCAL_BYTE,
    OP_GET_LOCAL_INT,
    OP_GET_LOCAL_FLOAT,
    OP_GET_LOCAL_ADDRESS,

    OP_SET_LOCAL_BYTE,
    OP_SET_LOCAL_INT,
    OP_SET_LOCAL_FLOAT,
    OP_SET_LOCAL_ADDRESS,

    OP_GET_GLOBAL_BYTE,
    OP_GET_GLOBAL_INT,
    OP_GET_GLOBAL_FLOAT,
    OP_GET_GLOBAL_ADDRESS,

    OP_SET_GLOBAL_BYTE,
    OP_SET_GLOBAL_INT,
    OP_SET_GLOBAL_FLOAT,
    OP_SET_GLOBAL_ADDRESS,

    // Print
    OP_PRINT_BOOL,
    OP_PRINT_INT,
    OP_PRINT_FLOAT,
    OP_PRINT_STRING,

    // Read
    OP_READ_BOOL,
    OP_READ_INT,
    OP_READ_FLOAT,
    OP_READ_STRING,

    // Jump
    OP_JUMP,
    OP_JUMP_IF_TRUE,
    OP_JUMP_IF_FALSE,

    // Functions
    OP_CALL,
    OP_RETURN_VOID,
    OP_RETURN_BYTE,
    OP_RETURN_INT,
    OP_RETURN_FLOAT,
    OP_RETURN_ADDRESS,
    
    // Array
    OP_SUBSCRIPT_GET_BYTE,
    OP_SUBSCRIPT_GET_INT,
    OP_SUBSCRIPT_GET_FLOAT,
    OP_SUBSCRIPT_GET_ADDRESS,

    OP_SUBSCRIPT_SET_BYTE,
    OP_SUBSCRIPT_SET_INT,
    OP_SUBSCRIPT_SET_FLOAT,
    OP_SUBSCRIPT_SET_ADDRESS,
} OpCode;


const char* opCodeName(OpCode op_code);


#endif

